
export const ADD_PLACES = "ADD_PLACES";
export const SET_ACTIVE_PLACE = "SET_ACTIVE_PLACE";


export const ADD_PLACE_TO_PLAN = "PUSH_PLACE_TO_PLAN";
export const REMOVE_PLACE_FROM_PLAN = "REMOVE_PLACE_FROM_PLAN";

export const SET_VIEW_MODE = "SET_VIEW_MODE"
export const SWITCH_BUILDER_MODE = "SWITCH_BUILDER_MODE"